/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Ashan
 */
public class VehicleDetails extends javax.swing.JFrame {

    /**
     * Creates new form VehicleDetails
     */
    public VehicleDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupVehicleType = new javax.swing.ButtonGroup();
        buttonGroupFuel = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        carRB = new javax.swing.JRadioButton();
        bikeRB = new javax.swing.JRadioButton();
        dualpRB = new javax.swing.JRadioButton();
        threewheelRB = new javax.swing.JRadioButton();
        otherRB = new javax.swing.JRadioButton();
        tractorRB = new javax.swing.JRadioButton();
        provinceTF = new javax.swing.JTextField();
        lettersTF = new javax.swing.JTextField();
        numbersTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        petrolRB = new javax.swing.JRadioButton();
        dieselRB = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        regCertUploadBtn = new javax.swing.JButton();
        vehicleRevLicenseBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nextBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        electricRB = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setText("Vehicle Details");

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel2.setText("Motor Vehicle No.");

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel3.setText("Motor Vehicle Type");

        carRB.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroupVehicleType.add(carRB);
        carRB.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        carRB.setText("Motor Car");
        carRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carRBActionPerformed(evt);
            }
        });

        bikeRB.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroupVehicleType.add(bikeRB);
        bikeRB.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        bikeRB.setText("Motor Bike");
        bikeRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bikeRBActionPerformed(evt);
            }
        });

        dualpRB.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroupVehicleType.add(dualpRB);
        dualpRB.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        dualpRB.setText("Dual Purpose");
        dualpRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dualpRBActionPerformed(evt);
            }
        });

        threewheelRB.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroupVehicleType.add(threewheelRB);
        threewheelRB.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        threewheelRB.setText("Three Wheelers");
        threewheelRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threewheelRBActionPerformed(evt);
            }
        });

        otherRB.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroupVehicleType.add(otherRB);
        otherRB.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        otherRB.setText("Other Land Vehicles");
        otherRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherRBActionPerformed(evt);
            }
        });

        tractorRB.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroupVehicleType.add(tractorRB);
        tractorRB.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        tractorRB.setText("Tractors");
        tractorRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tractorRBActionPerformed(evt);
            }
        });

        provinceTF.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        provinceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinceTFActionPerformed(evt);
            }
        });

        lettersTF.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lettersTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lettersTFActionPerformed(evt);
            }
        });

        numbersTF.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        numbersTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersTFActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel4.setText("( eg:- WP   AB   1234 )");

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel5.setText("Fuel Type");

        petrolRB.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroupFuel.add(petrolRB);
        petrolRB.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        petrolRB.setText("Petrol");
        petrolRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petrolRBActionPerformed(evt);
            }
        });

        dieselRB.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroupFuel.add(dieselRB);
        dieselRB.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        dieselRB.setText("Diesel");
        dieselRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dieselRBActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel6.setText("Upload Vehicle Registration Certificate");

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel7.setText("Upload Vehicle Revenue License");

        regCertUploadBtn.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        regCertUploadBtn.setText("Upload");
        regCertUploadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regCertUploadBtnActionPerformed(evt);
            }
        });

        vehicleRevLicenseBtn.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        vehicleRevLicenseBtn.setText("Upload");
        vehicleRevLicenseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleRevLicenseBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel8.setText("Maximum upload size 2MB (Accepted file type : PDF)");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel9.setText("Maximum upload size 2MB (Accepted file type : PDF)");

        nextBtn.setBackground(new java.awt.Color(204, 255, 255));
        nextBtn.setFont(new java.awt.Font("Georgia", 1, 15)); // NOI18N
        nextBtn.setText("Next");

        backBtn.setBackground(new java.awt.Color(204, 255, 255));
        backBtn.setFont(new java.awt.Font("Georgia", 1, 15)); // NOI18N
        backBtn.setText("Back");

        electricRB.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroupFuel.add(electricRB);
        electricRB.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        electricRB.setText("Electric");
        electricRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electricRBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(petrolRB)
                                        .addGap(34, 34, 34)
                                        .addComponent(dieselRB)
                                        .addGap(40, 40, 40)
                                        .addComponent(electricRB)))
                                .addGap(0, 431, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(carRB, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(106, 106, 106)
                                        .addComponent(jLabel1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(threewheelRB)
                                        .addGap(47, 47, 47)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bikeRB)
                                            .addComponent(tractorRB))
                                        .addGap(77, 77, 77)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(otherRB)
                                            .addComponent(dualpRB)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(provinceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(lettersTF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(numbersTF, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(152, 203, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(regCertUploadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(vehicleRevLicenseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(provinceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lettersTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numbersTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(carRB)
                                .addComponent(bikeRB)
                                .addComponent(dualpRB)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(threewheelRB)
                            .addComponent(tractorRB)
                            .addComponent(otherRB))
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(petrolRB)
                            .addComponent(dieselRB)
                            .addComponent(electricRB))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(regCertUploadBtn)
                                .addComponent(jLabel8)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(vehicleRevLicenseBtn)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextBtn)
                    .addComponent(backBtn))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carRBActionPerformed

    private void bikeRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bikeRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bikeRBActionPerformed

    private void dualpRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dualpRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dualpRBActionPerformed

    private void threewheelRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threewheelRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_threewheelRBActionPerformed

    private void otherRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherRBActionPerformed

    private void tractorRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tractorRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tractorRBActionPerformed

    private void provinceTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinceTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provinceTFActionPerformed

    private void lettersTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lettersTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lettersTFActionPerformed

    private void numbersTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbersTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numbersTFActionPerformed

    private void petrolRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petrolRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petrolRBActionPerformed

    private void dieselRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dieselRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dieselRBActionPerformed

    private void regCertUploadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regCertUploadBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regCertUploadBtnActionPerformed

    private void vehicleRevLicenseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleRevLicenseBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleRevLicenseBtnActionPerformed

    private void electricRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electricRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_electricRBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehicleDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JRadioButton bikeRB;
    private javax.swing.ButtonGroup buttonGroupFuel;
    private javax.swing.ButtonGroup buttonGroupVehicleType;
    private javax.swing.JRadioButton carRB;
    private javax.swing.JRadioButton dieselRB;
    private javax.swing.JRadioButton dualpRB;
    private javax.swing.JRadioButton electricRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lettersTF;
    private javax.swing.JButton nextBtn;
    private javax.swing.JTextField numbersTF;
    private javax.swing.JRadioButton otherRB;
    private javax.swing.JRadioButton petrolRB;
    private javax.swing.JTextField provinceTF;
    private javax.swing.JButton regCertUploadBtn;
    private javax.swing.JRadioButton threewheelRB;
    private javax.swing.JRadioButton tractorRB;
    private javax.swing.JButton vehicleRevLicenseBtn;
    // End of variables declaration//GEN-END:variables
}
