-- ============================================================================
-- Vehicle Registration System (VRS) - Oracle Database Migration Script
-- Migrated from MySQL (vrs_db.sql) to Oracle Database (12c/18c/19c/21c/23c/XE)
-- ============================================================================

-- Clean up existing tables safely if they already exist
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE checkstatus CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE vehicle_details CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE login CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- ----------------------------------------------------------------------------
-- 1. Table: login
-- Stores user accounts for authentication
-- ----------------------------------------------------------------------------
CREATE TABLE login (
    indexID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username  VARCHAR2(50) NOT NULL,
    email     VARCHAR2(50) NOT NULL CONSTRAINT uq_login_email UNIQUE,
    password  VARCHAR2(50) NOT NULL
);

-- ----------------------------------------------------------------------------
-- 2. Table: checkstatus
-- Stores application progress / status (1 to 5)
-- 1: Application Submitted
-- 2: Transferor Approved
-- 3: DMT Validator Approved
-- 4: Vehicle Registration Document Released (PDF)
-- 5: Vehicle Registration Document Released (via Post)
-- ----------------------------------------------------------------------------
CREATE TABLE checkstatus (
    applicationnum     VARCHAR2(8)  NOT NULL CONSTRAINT pk_checkstatus PRIMARY KEY,
    vehiclenum         VARCHAR2(20) NOT NULL,
    applicationstatus  VARCHAR2(1)  NOT NULL
);

CREATE INDEX idx_checkstatus_vehnum ON checkstatus(vehiclenum);

-- ----------------------------------------------------------------------------
-- 3. Table: vehicle_details
-- Stores registered vehicle details and associated documents
-- ----------------------------------------------------------------------------
CREATE TABLE vehicle_details (
    application_num      VARCHAR2(10) CONSTRAINT uq_veh_app_num UNIQUE,
    vehicle_type         VARCHAR2(25),
    vehicle_num          VARCHAR2(20),
    fuel_type            VARCHAR2(20),
    reg_certificate_pdf  BLOB,
    revenue_license_pdf  BLOB
);

CREATE INDEX idx_vehdetails_vehnum ON vehicle_details(vehicle_num);

-- ============================================================================
-- Seed Data / Initial Records
-- ============================================================================

-- Insert Login Users
INSERT INTO login (indexID, username, email, password) VALUES (1, 'Shamil Suraweera', 'shamil@vrs.com', '123');
INSERT INTO login (indexID, username, email, password) VALUES (2, 'Ashan Suraweera', 'ashan@vrs.com', '123');
INSERT INTO login (indexID, username, email, password) VALUES (3, 'John Doe', 'john@vrs.com', '123');

-- Insert Check Status Records
INSERT INTO checkstatus (applicationnum, vehiclenum, applicationstatus) VALUES ('1234AA', 'BX-7878', '1');
INSERT INTO checkstatus (applicationnum, vehiclenum, applicationstatus) VALUES ('1255AB', 'BO-7888', '3');
INSERT INTO checkstatus (applicationnum, vehiclenum, applicationstatus) VALUES ('1000AA', 'AS-2323', '5');
INSERT INTO checkstatus (applicationnum, vehiclenum, applicationstatus) VALUES ('0001AA', 'AB-2323', '4');
INSERT INTO checkstatus (applicationnum, vehiclenum, applicationstatus) VALUES ('0525YZ', 'AS-9090', '3');
INSERT INTO checkstatus (applicationnum, vehiclenum, applicationstatus) VALUES ('1687ZW', 'ASU-3434', '2');

-- Insert Vehicle Details
INSERT INTO vehicle_details (application_num, vehicle_type, vehicle_num, fuel_type, reg_certificate_pdf, revenue_license_pdf) 
VALUES ('0001AA', 'Car', 'AB-2323', 'Petrol', EMPTY_BLOB(), EMPTY_BLOB());

INSERT INTO vehicle_details (application_num, vehicle_type, vehicle_num, fuel_type, reg_certificate_pdf, revenue_license_pdf) 
VALUES ('1687ZW', 'Car', 'ASU-3434', 'Petrol', EMPTY_BLOB(), EMPTY_BLOB());

INSERT INTO vehicle_details (application_num, vehicle_type, vehicle_num, fuel_type, reg_certificate_pdf, revenue_license_pdf) 
VALUES ('0525YZ', 'Motor Bike', 'AS-9090', 'Diesel', EMPTY_BLOB(), EMPTY_BLOB());

INSERT INTO vehicle_details (application_num, vehicle_type, vehicle_num, fuel_type, reg_certificate_pdf, revenue_license_pdf) 
VALUES ('5224VD', 'Car', 'WW-9090', 'Petrol', EMPTY_BLOB(), EMPTY_BLOB());

COMMIT;

